stages:
- build_image
- test_image

variables:
  IMAGE_NAME_PRO: database_pro:$CI_COMMIT_REF_SLUG

production:
  stage: build_image
  script:
  - docker build --pull -t $IMAGE_NAME_PRO .

test:
  stage: test_image
  script:
  - docker run $IMAGE_NAME_PRO true
