stages:
- build
- test

variables:
  IMAGE_NAME: database:$CI_COMMIT_REF_SLUG

build_image:
  stage: build
  script:
  - docker build --pull -t $IMAGE_NAME .

test:
  stage: test
  script:
  - docker run $IMAGE_NAME true
